// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"context"
	"log"
	"time"

	"github.com/shamesjen/Orbital/kitex_gen/api"
	"github.com/shamesjen/Orbital/kitex_gen/api/test"

	"github.com/cloudwego/kitex/client"
)

func main() {
	h := server.Default()

	register(h)

	client, err := test.NewClient("test", client.WithHostPorts("0.0.0.0:9000"))
	if err != nil {
		log.Fatal(err)
	}

	req := &api.Request{Message: "kt is handsome"}
	resp, err := client.Reply(context.Background(), req)
	if err != nil {
		log.Fatal(err)
	}
	log.Println(resp)
	time.Sleep(time.Second)

	h.Spin() //need to replace this
	//hello world

}
